### ISSUE TITLE
reset() no working

### ISSUE THREAD

**Issue by WonJunior** [Nimzozo/Ab-Chess#23]
Documentation states "Create a new game and **set the chessboard to the initial starting position**."

This is not the case: simply call reset on your abChess object. The chessboard pieces remain in their position.

**Comment by Nimzozo** [comment]
You're right, it's a mistake in the documentation.

`reset` does not act on the chessboard :

https://github.com/Nimzozo/Ab-Chess/blob/b9303e38b7ab8dd30211da890d08431a82c6ba87/src/AbChess/AbChess-0.3.1.js#L1106

You can use the method `setFEN` to reset the board.

https://nimzozo.github.io/Ab-Chess/examples.html#set-fen
