### ISSUE TITLE
help

### ISSUE THREAD

**Issue by kovardanyan** [Nimzozo/Ab-Chess#24]
Hi!

I would like to make it so that the game starts not from the starting position of all the figures, but from the target position with the correct FEN, but I get an error. Can you tell me how to do it correctly?

**Comment by Nimzozo** [comment]
Hello,

You can set the board position with the [`setFEN()`](https://nimzozo.github.io/Ab-Chess/docs/reference.html#setFEN) method, but you cannot start the game from it. This method does not affect the game object.

At this moment, there is no method to start a game from a FEN string, so you have to make the game from the beginning.

I hope this will help you.
